### ISSUE TITLE
SAGE and CAGE No longer show in Loop Follow if using iAPS

### ISSUE THREAD

**Issue by flyingpie101** [loopandlearn/LoopFollow#227] opened 2023-10-03 21:13 UTC
We are using the latest LoopFollow as of Oct 3, 2023
And the latest NS and iAPS-Dev

LoopFollow no longer displays CAGE or SAGE.
NS does have values.

![image](https://github.com/loopandlearn/LoopFollow/assets/11539494/7e3c198c-7d06-4c13-9c81-c6cce5307863)
![image](https://github.com/loopandlearn/LoopFollow/assets/11539494/2118d08a-0920-4b5d-bb3d-746a4e8126c1)

**Comment by bjorkert** [comment] 2023-10-04 17:35
I am currently rewriting all Nightscout download functionality. Hopefully it will work better after that.

**Comment by aug0211** [comment] 2023-10-14 23:40
Are you on iOS 17?

If so, it’s not a FAX or Nightscout specific issue, it’s a Loop Follow issue (applies to FAX or Loop - anything on iOS 17).

This PR is the fix:

https://github.com/loopandlearn/LoopFollow/pull/231

**Comment by bjorkert** [comment] 2023-10-15 18:26
I have rewritten all ns download code, waiting for a review on that. It will be interesting to see if this solved the problem. @flyingpie101 you are welcome to try the "refactoring" branch.

**Comment by aug0211** [comment] 2023-10-15 20:38
The above branch will also work - I do not see any %20s in there with a quick search (this was the offending issue for iOS 17). Did a quick test and confirmed 🎉

@bjorkert did you make any other notable improvements/changes/new features in the NS refactor work you did?

**Comment by flyingpie101** [comment] 2023-10-15 22:55
In the refactor branch, SAGE and CAGE are downloading again. ;)

**Comment by bjorkert** [comment] 2023-10-16 06:54
> The above branch will also work - I do not see any %20s in there with a quick search (this was the offending issue for iOS 17). Did a quick test and confirmed 🎉
> 
> @bjorkert did you make any other notable improvements/changes/new features in the NS refactor work you did?

I have removed separate downloading of carbs today (since it is in treatments anyway), also it will primary get CAGE+SAGE from treatments, but if those are older it will do a deeper download of them - but only once, after that CAGE/SAGE are expected to be in the 24h download of treatments. I hope this will save some battery.

I am also filtering out future SAGE since i suspect there is a bug in loop dev uploading future sensor changes (year 2157).

**Comment by aug0211** [comment] 2023-10-18 01:58
Very nice 👏

**Comment by bjornoleh** [comment] 2024-01-13 10:51
It seems this issue can be closed now.

**Closed** 2024-01-13 16:33 UTC
